apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: auth-service
  template:
    metadata:
      labels:
        pod: auth-service
    spec:
      containers:
        - name: auth-container
          image: nguyenminhtiend/auth-service:v3
          ports:
            - containerPort: 3001
