apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - http:
        paths:
          - path: /user/*
            backend:
              serviceName: user-svc
              servicePort: 3000
          - path: /auth/*
            backend:
              serviceName: auth-svc
              servicePort: 3001
